version: 2

models:
  - name: fct_bookings
    description: Fact table containing transactional data related to bookings.
    columns:
      - name: booking_id
        description: Unique identifier for each booking.
        tests:
          - unique
          - not_null

      - name: listing_id
        description: Foreign key linking to dim_listings.
        tests:
          - relationships:
              to: ref('dim_listings')
              field: listing_id

      - name: customer_id
        description: Foreign key linking to dim_customers.
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id

      - name: check_in
        description: Check-in date for the booking.

      - name: check_out
        description: Check-out date for the booking.

      - name: total_price
        description: Total amount paid for the booking duration.
        tests:
          - not_null

      - name: length_of_stay
        description: Number of nights between check-in and check-out.

      - name: revenue_per_night
        description: Total revenue divided by the length of stay.

      - name: is_checked_in
        description: Boolean flag indicating whether the guest has checked in (TRUE/FALSE).

  - name: fct_reviews
    description: Fact table containing customer reviews and feedback.
    columns:
      - name: review_id
        description: Unique identifier for each review.
        tests:
          - unique
          - not_null
          
      - name: listing_id
        description: Foreign key linking to dim_listings.
        tests:
          - relationships:
              to: ref('dim_listings')
              field: listing_id

      - name: reviewer_id
        description: Foreign key linking to dim_customers.
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id

      - name: review_date
        description: Date when the review was posted.

      - name: reviewer_name
        description: Name of the person who left the review.

      - name: comments
        description: Textual feedback provided by the customer.

  - name: fct_maintenance
    description: Fact table tracking maintenance issues and resolution times.
    columns:
      - name: listing_id
        description: Foreign key linking to dim_listings.
        tests:
          - relationships:
              to: ref('dim_listings')
              field: listing_id

      - name: issue_type
        description: Category of maintenance issue (e.g., Plumbing, Electrical, Cleaning).

      - name: resolution_time
        description: Time taken to resolve the maintenance issue (in hours).

  - name: fct_events
    description: Fact table tracking external events that may impact bookings.
    columns:
      - name: booking_id
        description: Foreign key linking to fact_bookings.
        tests:
          - relationships:
              to: ref('fct_bookings')
              field: booking_id

      - name: event_type
        description: Category of event impacting the booking (e.g., Concert, Festival).
        
      - name: event_impact
        description: Numerical score representing the impact of the event on bookings.
